version: "3.8"

networks:
  boiler-plate-network:
    driver: bridge

volumes:
  boiler-plate-db:
    driver: local

services:
  server:
    image: nginx:1.25.3
    container_name: server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d:ro
      - ./data/nginx/app:/app:ro
      # - ./data/certbot/conf:/etc/letsencrypt:ro
      # - ./data/certbot/www:/var/www/certbot:ro
    networks:
      - boiler-plate-network

  # certbot:
  #   image: certbot/certbot:v2.7.3
  #   container_name: certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt:rw
  #     - ./data/certbot/www:/var/www/certbot:rw

  db:
    image: postgres:16.0-alpine3.18
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 4321:5432
    volumes:
      - boiler-plate-db:/var/lib/postgresql/data
    networks:
      - boiler-plate-network

  backend:
    image: boiler-plate/backend:latest
    build:
      context:
        ../backend
    container_name: backend
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Jwt__PrivateKey: ${BOILER_PLATE_JWT_PRIVATE_KEY}
    volumes:
      - ./file-storage-root:/app/file-storage-root:rw
    depends_on:
      - db
    networks:
      - boiler-plate-network

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    restart: always
    ports:
      - 9091:9091
    environment:
      KAFKA_LISTENERS: BROKER://kafka1:29091,EXTERNAL://0.0.0.0:9091,CONTROLLER://kafka1:19091
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:29091,EXTERNAL://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:19091,2@kafka2:19092,3@kafka3:19093'
      KAFKA_JMX_PORT: 9991
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9991
      CLUSTER_ID: 'UMcrVmvcQ6CaKkl1fCwYHw'
    volumes:
      - ./kafka-data/1/logs:/tmp/kafka-logs
      - ./kafka-data/1/data:/var/lib/kafka/data
      - ./kafka-data/1/secrets:/etc/kafka/secrets
    networks:
      - boiler-plate-network

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: BROKER://kafka2:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka2:19092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:19091,2@kafka2:19092,3@kafka3:19093'
      KAFKA_JMX_PORT: 9992
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9992
      CLUSTER_ID: 'UMcrVmvcQ6CaKkl1fCwYHw'
    volumes:
      - ./kafka-data/2/logs:/tmp/kafka-logs
      - ./kafka-data/2/data:/var/lib/kafka/data
      - ./kafka-data/2/secrets:/etc/kafka/secrets
    networks:
      - boiler-plate-network

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka3
    restart: always
    ports:
      - 9093:9093
    environment:
      KAFKA_LISTENERS: BROKER://kafka3:29093,EXTERNAL://0.0.0.0:9093,CONTROLLER://kafka3:19093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka3:29093,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:19091,2@kafka2:19092,3@kafka3:19093'
      KAFKA_JMX_PORT: 9993
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9993
      CLUSTER_ID: 'UMcrVmvcQ6CaKkl1fCwYHw'
    volumes:
      - ./kafka-data/3/logs:/tmp/kafka-logs
      - ./kafka-data/3/data:/var/lib/kafka/data
      - ./kafka-data/3/secrets:/etc/kafka/secrets
    networks:
      - boiler-plate-network

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 18080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka1:29091
      KAFKA_CLUSTERS_0_METRICS_PORT: 9991
      KAFKA_CLUSTERS_1_NAME: kafka2
      KAFKA_CLUSTERS_1_BOOTSTRAP_SERVERS: kafka2:29092
      KAFKA_CLUSTERS_1_METRICS_PORT: 9992
      KAFKA_CLUSTERS_2_NAME: kafka3
      KAFKA_CLUSTERS_2_BOOTSTRAP_SERVERS: kafka3:29093
      KAFKA_CLUSTERS_2_METRICS_PORT: 9993
      DYNAMIC_CONFIG_ENABLED: 'true'
      AUTH_TYPE: LOGIN_FORM
      SPRING_SECURITY_USER_NAME: kafka-ui-admin
      SPRING_SECURITY_USER_PASSWORD: Admin321
    networks:
      - boiler-plate-network
